### ISSUE TITLE
Question rather than issue ;) 

### ISSUE THREAD

**Issue by jmcazaux** [Vermoot/qmk_keymaps#1]
I stumbled upon your keymap [here](https://keymapdb.com/keymaps/Vermoot/) while I was looking for one for my Kyria.

Any chance you can share how you generated those great graphics?

Thanks in advance,
JM

**Comment by Vermoot** [comment]
Hi!
Unfortunately I didn't *generate* them, but I made them manually with Sketch on macOS (you could also use Figma on all platforms)
